Fix dock icon in Java 21+
Conditionally adds exports for java.desktop/com.apple.eawt if OS is Mac. Otherwise default Java logo is used, and error is logged:

Error setting dock icon image
  java.lang.IllegalAccessException: class runwar.Server cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module